// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxT22XFF2fngwdjqtewff-tCtRoY3oio',
    appId: '1:626749773784:android:cfcbc61fa9c0dd20a744ad',
    messagingSenderId: '626749773784',
    projectId: 'flutter-apps-36f38',
    databaseURL: 'https://flutter-apps-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-36f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvsl5kcJjudSOOZoc0iAjZrxvaAc2WrM',
    appId: '1:626749773784:ios:386c0fb14aedcdc8a744ad',
    messagingSenderId: '626749773784',
    projectId: 'flutter-apps-36f38',
    databaseURL: 'https://flutter-apps-36f38-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-36f38.firebasestorage.app',
    androidClientId: '626749773784-ins3jrgt1ev5v2o8clkoscnq4f6dlcsf.apps.googleusercontent.com',
    iosClientId: '626749773784-t73udcb5c2b97urs0269761pkprhbbeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballLiveScoreExercise',
  );
}
